services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - /mnt/e/database/Config:/app/config
      - /mnt/e/database/Schema:/app/schema
      - /mnt/e/database/SP:/app/SP
      - /mnt/e/Repo/Spark-Bitnami/mnt/apps/logs:/app/logs
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Allows access to host services
      
networks:
  app-network:
    driver: bridge