services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - /mnt/e/database/Config:/app/config
    networks:
      - app-network

networks:
  app-network:
    driver: bridge